baseurl = "https://mfy.netlify.com/"
title = "Fatih's Data Incubator Project Page"

theme = "hugo-coder"
languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[params]
    author = "Mehmet Fatih Yasar"
    description = "Data Incubator Project Web Site"
    keywords = "project,developer,data"
    info = "Greatest Candidate Ever :)"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
	custom_css = []

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/Ntnu2014/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/mfyasar1/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/mehmet-fatih-yasar-222a7b13a/"


[[menu.main]]
    name = "About |"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = " Project |"
    weight = 2
    url  = "/project/"
[[menu.main]]
    name = " Data |"
    weight = 3
    url  = "/data/all.xlsx"
[[menu.main]]
    name = " PDF"
    weight = 4
    url = "/document.pdf"
